apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}
spec:
  type: "ExternalName"
  externalName: {{ .Values.service.externalName | quote }}
  ports:
  {{- range .Values.service.ports }}
  - port: {{ .port }}
  {{- end }}